version: '3.8'

services:
  # Go 后端
  go-backend:
#    build:
#      context: .
#      dockerfile: Dockerfile.go
    image: 192.168.1.207:803/ugreen-metric/go-backend:v1
    container_name: dev-metric-backend
    ports:
      - "18086:18080"
    environment:
      - DB_HOST=${DB_HOST:-192.168.1.225}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-admin123}
      - DB_NAME=${DB_NAME:-dev_metric}
      - STARROCKS_HOST=${STARROCKS_HOST:-192.168.1.177}
      - STARROCKS_PORT=${STARROCKS_PORT:-6033}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
    depends_on:
      - redis
    restart: unless-stopped

  # Python AI 服务
  python-ai:
#    build:
#      context: .
#      dockerfile: Dockerfile.ai
    image: 192.168.1.207:803/ugreen-metric/ai-backend:v1
    container_name: dev-metric-ai
    ports:
      - "18081:18081"
    environment:
      - USE_SEMANTIC_LAYER=1
      - GO_API_BASE=http://go-backend:18080
      - TENCENT_API_KEY=${TENCENT_API_KEY}
      - TENCENT_API_URL=${TENCENT_API_URL}
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
      - INTENT_MODEL_URL=http://intent-model:18082
    depends_on:
      - go-backend
    restart: unless-stopped

  # 意图识别模型服务
  intent-model:
#    build:
#      context: .
#      dockerfile: Dockerfile.model
    image: 192.168.1.207:803/ugreen-metric/intent:v1
    container_name: dev-metric-intent
    ports:
      - "18082:18082"
    environment:
      - DB_HOST=${DB_HOST:-192.168.1.225}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-admin123}
      - DB_NAME=${DB_NAME:-dev_metric}
    restart: unless-stopped

  # Vue 前端
  web-frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile.web
    image: 192.168.1.207:803/ugreen-metric/web:v1
    container_name: dev-metric-web
    ports:
      - "3002:3002"
    depends_on:
      - go-backend
      - python-ai
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7-alpine
    container_name: dev-metric-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
